name: Detox_e2e_iOS

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Cache Pods
      uses: actions/cache@v2
      id: podcache
      with:
        path: ios/Pods
        key: pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Install Detox Dependencies
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && npx pod-install && cd -

    - name: Rebuild framwork cahe detox
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        yarn detox clean-framework-cache && yarn detox build-framework-cache

    - name: Build Detox
      run: |
        yarn detox build -s -c ios.sim.release --cleanup

    - name: Run tests Cucumber
      run: |
        yarn cucmber